spring.application.name=chamavault
#server.port=8082

##################################################################################################################
############################################### DB CONFIGS #######################################################
##################################################################################################################
spring.datasource.url=jdbc:postgresql://ep-summer-king-ac8yfurf-pooler.sa-east-1.aws.neon.tech:5432/chamavault?currentSchema=mvp
spring.datasource.username=app_user
spring.datasource.password=6BKrFhG4bO17
spring.datasource.driver-class-name=org.postgresql.Driver

##################################################################################################################
############################################### JPA ##############################################################
##################################################################################################################
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database=POSTGRESQL

##################################################################################################################
############################################### SECURITY #########################################################
##################################################################################################################
jwt.secret=zw0l3ONPYVp4W50f1wfSzatashqQh1zBDabIqiDiD0S
jwt.expiration=86400000

##################################################################################################################
############################################### LOGGING ##########################################################
##################################################################################################################
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG


# Expose the health endpoint details
management.endpoint.health.show-details=always

# Expose all actuator endpoints (or selectively expose 'health')
management.endpoints.web.exposure.include=health


#dada_labs_two_invoices_api_key=bec3d840-1005-4621-85d6-281cb75bc6e2
#lnbits.base-url=https://demo.lnbits.com
#lnbits.admin-key=f6217a501c1d421a8b8a81abcb1aa910
#lnbits.user-id=ef1cc8386895499f99b5f8dcb2bd10eb

lnbits.base-url=https://emptydoves2.lnbits.com
lnbits.admin-key=25e03cf11f1748d3a2721d6df3c23e28
lnbits.invoice-key=c7953c511d644a558903ef3b1f9ef02d
lnbits.user-id=36d03ea1e09f4259916fb2ff848f5696
lnbits.wallet-id=44f42fe025224985b3c6a233e10dc864
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=DEBUG


###################################################################################################################
############################################### PAYSTACK ##########################################################
###################################################################################################################
paystack.payments.public-key=pk_test_0b168a8c0c8ff671bb9806a92e89e32acef76ab0
paystack.payments.secret-key=sk_test_c0ad87612f700939496d4ea940296360c16863ff
paystack.payments.base-url=https://api.paystack.co