spring.application.name=chamavault
#server.port=8082

##################################################################################################################
############################################### DB CONFIGS #######################################################
##################################################################################################################
spring.datasource.url=jdbc:postgresql://ep-summer-king-ac8yfurf-pooler.sa-east-1.aws.neon.tech:5432/dada_labs_2?currentSchema=dev
spring.datasource.username=app_user
spring.datasource.password=6BKrFhG4bO17
spring.datasource.driver-class-name=org.postgresql.Driver

##################################################################################################################
############################################### JPA ##############################################################
##################################################################################################################
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database=POSTGRESQL

##################################################################################################################
############################################### SECURITY #########################################################
##################################################################################################################
jwt.secret=zw0l3ONPYVp4W50f1wfSzatashqQh1zBDabIqiDiD0S
jwt.expiration=86400000

##################################################################################################################
############################################### LOGGING ##########################################################
##################################################################################################################
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG


# Expose the health endpoint details
management.endpoint.health.show-details=always

# Expose all actuator endpoints (or selectively expose 'health')
management.endpoints.web.exposure.include=health


#dada_labs_two_invoices_api_key=bec3d840-1005-4621-85d6-281cb75bc6e2
#lnbits.base-url=https://demo.lnbits.com
#lnbits.admin-key=f6217a501c1d421a8b8a81abcb1aa910
#lnbits.user-id=ef1cc8386895499f99b5f8dcb2bd10eb

lnbits.base-url=https://demo.lnbits.com
lnbits.admin-key=1a74377235df4c60bec65a4c200596cf
lnbits.invoice-key=b2874f4d396f4d1b9482bee1ec15cdb4
lnbits.wallet-id=d0ca407a1cf646cda9161b2b42b091c3
lnbits.user-id=d727cba226cb4ec3885f5c893bc2640e
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=DEBUG


###################################################################################################################
############################################### PAYSTACK ##########################################################
###################################################################################################################
paystack.payments.public-key=pk_test_0b168a8c0c8ff671bb9806a92e89e32acef76ab0
paystack.payments.secret-key=sk_test_c0ad87612f700939496d4ea940296360c16863ff
paystack.payments.base-url=https://api.paystack.co