spring.application.name=chamavault
server.port=8080

##################################################################################################################
############################################### DB CONFIGS #######################################################
##################################################################################################################
spring.datasource.url=jdbc:postgresql://ep-summer-king-ac8yfurf-pooler.sa-east-1.aws.neon.tech:5432/dada_labs_2?currentSchema=dev
spring.datasource.username=app_user
spring.datasource.password=6BKrFhG4bO17
spring.datasource.driver-class-name=org.postgresql.Driver

##################################################################################################################
############################################### JPA ##############################################################
##################################################################################################################
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database=POSTGRESQL

##################################################################################################################
############################################### SECURITY #########################################################
##################################################################################################################
jwt.secret=zw0l3ONPYVp4W50f1wfSzatashqQh1zBDabIqiDiD0S
jwt.expiration=86400000

##################################################################################################################
############################################### LOGGING ##########################################################
##################################################################################################################
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG


# Expose the health endpoint details
management.endpoint.health.show-details=always

# Expose all actuator endpoints (or selectively expose 'health')
management.endpoints.web.exposure.include=health
