package com.dada_labs_two.chamavault.chama.activities;
public enum ChamaActivityType {
 CHAMA_CREATED, CHAMA_UPDATED, MEMBER_JOIN_REQUESTED, MEMBER_JOINED, MEMBER_APPROVED, MEMBER_REJECTED,
 MEMBER_SUSPENDED, MEMBER_REMOVED, INVITE_CREATED, INVITE_USED, INVITE_PAUSED,
 POOLING_WALLET_CREATED, POOLING_CYCLE_STARTED, POOLING_CYCLE_CLOSED, POOLING_CONTRIBUTION_PAID,
 POOLING_CONTRIBUTION_PARTIALLY_PAID, POOLING_TARGET_REACHED,
 ROTATION_CYCLE_STARTED, ROTATION_CYCLE_CLOSED, ROTATION_CONTRIBUTION_PAID,
 ROTATION_CONTRIBUTION_PARTIALLY_PAID, ROTATION_WAITING_FOR_MEMBERS, ROTATION_MEMBER_SKIPPED,
 WALLET_TOPPED_UP, PAYOUT_REQUESTED, PAYOUT_COMPLETED,
 GOVERNANCE_REQUEST_CREATED, GOVERNANCE_VOTE_CAST, GOVERNANCE_REQUEST_APPROVED,
 GOVERNANCE_REQUEST_REJECTED, GOVERNANCE_REQUEST_EXECUTED, FINE_ISSUED,
 CONTRIBUTION_AMOUNT_CHANGED, CONTRIBUTION_FREQUENCY_CHANGED, APPROVAL_POLICY_CHANGED,
 MAXIMUM_MEMBERS_CHANGED, CHAMA_CONFIG_CHANGED
}
